# Total number of nodes in the WSN 
NO_OF_NODES: 100

# 
NO_OF_FAULTY_NODES: 25

NODE_AVG_VALUE_MIN: 23.5
NODE_AVG_VALUE_MAX: 25.3

NODE_FAULT_VAL_MIN: 53.2
NODE_FAULT_VAL_MAX: 80.2

STAT_METHOD: 'MAD' # 'IQR', 'QN' , 'SN', 'SD'

# Nodes are placed between (0, 0) --> (X_MAX, Y_MAX)
X_MAX: 500 
Y_MAX: 500 

# Transmission range of node are (20 meter)
TX_RANGE_OF_NODE: 40

# Protocol for sending data to the gateway or sink node.
ROUTING_PROTOCOL: None

# Initial power of the node
INITIAL_POWER: 10